version: "3"
services:

  csharp-service:
    build:
      context: ./csharp
    container_name: csharp-service
    ports:
      - "9999:9999"

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-submit:
    build:
      context: ./job
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker
    environment:
      - "ENABLE_INIT_DAEMON=false"
