name: Spark 3 / Java 11
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java, SBT
        uses: olafurpg/setup-scala@v11
        with:
          java-version: 'adopt@1.11'
      - name: Build and test
        run: sbt -Dspark.testVersion=3.1.2 ++2.12.10 clean scalastyle test:scalastyle mimaReportBinaryIssues
